-- Migrate existing content to database
-- Run this in Supabase SQL Editor after creating the content table

-- Hero section
INSERT INTO content (id, section, key, lang, value) VALUES
('hero-badge-mn', 'hero', 'badge', 'mn', 'Монголын анхны хувийн рашаан сувилал · 2003 оноос'),
('hero-badge-en', 'hero', 'badge', 'en', 'Mongolia''s First Private Mineral Resort · Est. 2003'),
('hero-tag1-mn', 'hero', 'tag1', 'mn', 'Амралт'),
('hero-tag1-en', 'hero', 'tag1', 'en', 'Rest'),
('hero-tag2-mn', 'hero', 'tag2', 'mn', 'рашаан'),
('hero-tag2-en', 'hero', 'tag2', 'en', 'Springs'),
('hero-tag3-mn', 'hero', 'tag3', 'mn', 'сэргэлт'),
('hero-tag3-en', 'hero', 'tag3', 'en', 'Renewal'),
('hero-desc-mn', 'hero', 'desc', 'mn', '«Хужиртын хөх сувд» халуун рашаан, «Хужиртын хар сувд» эмчилгээний шавраар байгалийн аргаар эрүүлжин урт насалъя.'),
('hero-desc-en', 'hero', 'desc', 'en', 'Restore yourself through the world-renowned «Blue Pearl» hot springs and «Black Pearl» therapeutic mud of Khujirt.'),
('hero-cta1-mn', 'hero', 'cta1', 'mn', 'Захиалга өгөх'),
('hero-cta1-en', 'hero', 'cta1', 'en', 'Book Your Stay'),
('hero-cta2-mn', 'hero', 'cta2', 'mn', 'Эмчилгээ үзэх'),
('hero-cta2-en', 'hero', 'cta2', 'en', 'View Treatments'),
('hero-phone-mn', 'hero', 'phone', 'mn', 'Захиалгын утас'),
('hero-phone-en', 'hero', 'phone', 'en', 'Booking hotline'),

-- About section
('about-badge-mn', 'about', 'badge', 'mn', 'Бидний тухай'),
('about-badge-en', 'about', 'badge', 'en', 'About Us'),
('about-title-mn', 'about', 'title', 'mn', 'Сэмжид Хужирт Рашаан Сувилал'),
('about-title-en', 'about', 'title', 'en', 'Semjid Khujirt Resort'),
('about-p1-mn', 'about', 'p1', 'mn', 'Сэмжид Хужирт рашаан сувилал нь анх 2003 онд байгуулагдсан Монголын анхны сувиллуудын нэг юм.'),
('about-p1-en', 'about', 'p1', 'en', 'Founded in 2003 as one of Mongolia''s first private mineral resorts.'),
('about-p2-mn', 'about', 'p2', 'mn', 'Дэлхийн соёлын өвд бүртгэгдсэн Орхон голын сав газар, эртний Хархорин, Эрдэнэзуу хийд, Төвхөн хийд, Шанх хийд, Улаан цутгалан зэрэг байгалийн үзэсгэлэнт газруудтай ойролцоо байрладаг.'),
('about-p2-en', 'about', 'p2', 'en', 'Located near the UNESCO-listed Orkhon Valley, ancient Kharkhorin, Erdene Zuu monastery, and scenic natural landmarks.'),
('about-p3-mn', 'about', 'p3', 'mn', '«Хужиртын хөх сувд» халуун рашаан, «Хужиртын хар сувд» эмчилгээний шавраар голлон эмчилгээ хийхийн сацуу европ болон монгол уламжлалт эмчилгээнүүдийг хийдэг.'),
('about-p3-en', 'about', 'p3', 'en', 'Treatments centre on the «Blue Pearl» hot springs and «Black Pearl» mud, combined with European and Mongolian therapies.'),
('about-p4-mn', 'about', 'p4', 'mn', 'Нарийн мэргэжлийн эмч болон үйлчилгээний 50 гаруй ажилтантай. Өвлийн улиралд 180, зуны улиралд 250 гаруй зочин нэгэн зэрэг хүлээн авах хүчин чадалтай.'),
('about-p4-en', 'about', 'p4', 'en', '50+ specialist doctors and staff. Capacity: 90 winter / 180+ summer guests.'),
('about-p5-mn', 'about', 'p5', 'mn', 'Улаанбаатараас 380 км. Хатуу хучилттай засмал замаар холбогдсон. Жилийн 4 улиралд нээлттэй.'),
('about-p5-en', 'about', 'p5', 'en', '380 km from Ulaanbaatar via paved road. Open all four seasons.'),
('about-more-mn', 'about', 'more', 'mn', 'Дэлгэрэнгүй унших →'),
('about-more-en', 'about', 'more', 'en', 'Read Full Story →'),
('about-s1n-mn', 'about', 's1n', 'mn', '2003'),
('about-s1n-en', 'about', 's1n', 'en', '2003'),
('about-s1l-mn', 'about', 's1l', 'mn', 'Үүссэн он'),
('about-s1l-en', 'about', 's1l', 'en', 'Founded'),
('about-s2n-mn', 'about', 's2n', 'mn', '50+'),
('about-s2n-en', 'about', 's2n', 'en', '50+'),
('about-s2l-mn', 'about', 's2l', 'mn', 'Мэргэжилтэн'),
('about-s2l-en', 'about', 's2l', 'en', 'Specialists'),
('about-s3n-mn', 'about', 's3n', 'mn', '250'),
('about-s3n-en', 'about', 's3n', 'en', '250'),
('about-s3l-mn', 'about', 's3l', 'mn', 'Зочны багтаамж'),
('about-s3l-en', 'about', 's3l', 'en', 'Guest Capacity'),
('about-s4n-mn', 'about', 's4n', 'mn', '4×'),
('about-s4n-en', 'about', 's4n', 'en', '4×'),
('about-s4l-mn', 'about', 's4l', 'mn', 'Улирал нээлттэй'),
('about-s4l-en', 'about', 's4l', 'en', 'Seasons Open'),

-- Conditions section
('conditions-badge-mn', 'conditions', 'badge', 'mn', 'Эмчилдэг өвчнүүд'),
('conditions-badge-en', 'conditions', 'badge', 'en', 'Conditions We Treat'),
('conditions-title-mn', 'conditions', 'title', 'mn', 'Хужиртын рашаан, шавраар эмчилдэг өвчнүүд'),
('conditions-title-en', 'conditions', 'title', 'en', 'Conditions Treated with Khujirt Springs & Mud'),
('conditions-note-mn', 'conditions', 'note', 'mn', 'Тэр дундаа нуруу, үе мөчний өвчинд онцгой үр дүнтэй.'),
('conditions-note-en', 'conditions', 'note', 'en', 'Especially effective for spinal and joint conditions.'),

-- Footer section
('footer-tagline-mn', 'footer', 'tagline', 'mn', 'Монголын анхны хувийн рашаан сувилал. Орхон голын хөндий, Хужирт сум.'),
('footer-tagline-en', 'footer', 'tagline', 'en', 'Mongolia''s first private mineral resort. Orkhon Valley, Khujirt soum.'),
('footer-addr-mn', 'footer', 'addr', 'mn', 'Өвөрхангай аймаг, Хужирт сум'),
('footer-addr-en', 'footer', 'addr', 'en', 'Khujirt soum, Uvurkhangai aimag'),
('footer-nav-mn', 'footer', 'nav', 'mn', 'Цэс'),
('footer-nav-en', 'footer', 'nav', 'en', 'Navigation'),
('footer-contact-mn', 'footer', 'contact', 'mn', 'Холбоо барих'),
('footer-contact-en', 'footer', 'contact', 'en', 'Contact Us'),
('footer-rights-mn', 'footer', 'rights', 'mn', 'Бүх эрх хамгаалагдсан.'),
('footer-rights-en', 'footer', 'rights', 'en', 'All rights reserved.'),

-- Images section
('images-hero_main-mn', 'images', 'hero_main', 'mn', '/images/hero-main.png'),
('images-hero_main-en', 'images', 'hero_main', 'en', '/images/hero-main.png'),
('images-logo-mn', 'images', 'logo', 'mn', '/images/logo.png'),
('images-logo-en', 'images', 'logo', 'en', '/images/logo.png'),
('images-about_image-mn', 'images', 'about_image', 'mn', '/images/about.jpg'),
('images-about_image-en', 'images', 'about_image', 'en', '/images/about.jpg'),
('images-resort_main-mn', 'images', 'resort_main', 'mn', '/images/resort-main.jpg'),
('images-resort_main-en', 'images', 'resort_main', 'en', '/images/resort-main.jpg'),
('images-resort_nature-mn', 'images', 'resort_nature', 'mn', '/images/resort-nature.jpg'),
('images-resort_nature-en', 'images', 'resort_nature', 'en', '/images/resort-nature.jpg'),
('images-referral_letter-mn', 'images', 'referral_letter', 'mn', ''),
('images-referral_letter-en', 'images', 'referral_letter', 'en', '')

ON CONFLICT (id) DO UPDATE SET
  value = EXCLUDED.value,
  image_url = EXCLUDED.image_url,
  updated_at = NOW();